//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cong_ty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cong_ty()
        {
            this.cong_viec = new HashSet<cong_viec>();
        }
    
        public int id { get; set; }
        public string ten_cong_ty { get; set; }
        public string dia_chi { get; set; }
        public string gioi_thieu_cong_ty { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string mat_khau { get; set; }
        public string trang_web { get; set; }
        public string anh_dai_dien { get; set; }
        public string anh_bia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cong_viec> cong_viec { get; set; }
    }
}
