//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cong_viec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cong_viec()
        {
            this.ung_tuyen = new HashSet<ung_tuyen>();
        }
    
        public int id { get; set; }
        public int id_cong_ty { get; set; }
        public string ten_cong_viec { get; set; }
        public Nullable<decimal> muc_luong_min { get; set; }
        public Nullable<int> so_luong_tuyen { get; set; }
        public string hinh_thuc_lam_viec { get; set; }
        public string cap_bac { get; set; }
        public string yc_gioi_tinh { get; set; }
        public Nullable<System.DateTime> ngay_het_han { get; set; }
        public string kinh_nghiem { get; set; }
        public string dia_diem_lam_viec { get; set; }
        public string mo_ta { get; set; }
        public string yeu_cau_ung_vien { get; set; }
        public string quyen_loi { get; set; }
        public string cach_thuc_ung_tuyen { get; set; }
        public string vi_tri { get; set; }
        public Nullable<decimal> muc_luong_max { get; set; }
    
        public virtual cong_ty cong_ty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ung_tuyen> ung_tuyen { get; set; }
    }
}
