//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobFinderEntities : DbContext
    {
        public JobFinderEntities()
            : base("name=JobFinderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cong_ty> cong_ty { get; set; }
        public virtual DbSet<cong_viec> cong_viec { get; set; }
        public virtual DbSet<nguoi_tim_viec> nguoi_tim_viec { get; set; }
        public virtual DbSet<ung_tuyen> ung_tuyen { get; set; }
        public virtual DbSet<ung_tuyen_thanh_cong> ung_tuyen_thanh_cong { get; set; }

    }
}
