//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_tim_viec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoi_tim_viec()
        {
            this.ung_tuyen = new HashSet<ung_tuyen>();
        }
    
        public int id { get; set; }
        public string ho_ten { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string mat_khau { get; set; }
        public string dia_chi { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string gioi_tinh { get; set; }
        public string trinh_do_hoc_van { get; set; }
        public string kinh_nghiem { get; set; }
        public string ky_nang { get; set; }
        public string chung_chi { get; set; }
        public string khoa_hoc { get; set; }
        public string du_an { get; set; }
        public string san_pham { get; set; }
        public string hoat_dong_tinh_nguyen { get; set; }
        public string anh_dai_dien { get; set; }
        public string anh_bia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ung_tuyen> ung_tuyen { get; set; }
    }
}
