//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ung_tuyen_thanh_cong
    {
        public int id { get; set; }
        public int id_ung_tuyen { get; set; }
        public Nullable<bool> da_ung_tuyen { get; set; }
        public Nullable<System.DateTime> ngay_ung_tuyen { get; set; }
        public Nullable<System.DateTime> ngay_phong_van { get; set; }
        public string ket_qua_phong_van { get; set; }
        public Nullable<System.DateTime> ngay_lam_viec { get; set; }
        public Nullable<decimal> muc_luong { get; set; }
    
        public virtual ung_tuyen ung_tuyen { get; set; }
    }
}
